# Generated by Django 4.2.27 on 2026-03-03 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.hashers import make_password


def seed_default_company(apps, schema_editor):
    Company = apps.get_model("inventory", "Company")
    UserCompany = apps.get_model("inventory", "UserCompany")
    User = apps.get_model("auth", "User")

    Category = apps.get_model("inventory", "Category")
    Unit = apps.get_model("inventory", "Unit")
    Product = apps.get_model("inventory", "Product")
    Deposit = apps.get_model("inventory", "Deposit")
    Movement = apps.get_model("inventory", "Movement")
    Client = apps.get_model("inventory", "Client")
    Supplier = apps.get_model("inventory", "Supplier")
    PriceList = apps.get_model("inventory", "PriceList")
    AuditLog = apps.get_model("inventory", "AuditLog")

    company, _ = Company.objects.get_or_create(
        code="default",
        defaults={"name": "Empresa Default"},
    )

    for model in [Category, Unit, Product, Deposit, Movement, Client, Supplier, PriceList, AuditLog]:
        model.objects.filter(company__isnull=True).update(company=company)

    for user in User.objects.all():
        UserCompany.objects.get_or_create(user=user, defaults={"company": company})

    if not User.objects.filter(username="admin").exists():
        admin = User.objects.create(
            username="admin",
            is_active=True,
            is_staff=True,
            is_superuser=True,
            password=make_password("admin123"),
        )
        UserCompany.objects.get_or_create(user=admin, defaults={"company": company})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='inventory.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='movement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.company'),
        ),
        migrations.RunPython(seed_default_company, migrations.RunPython.noop),
    ]
