# Generated by Django 4.2.27 on 2026-03-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_category_name_alter_deposit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operador'), ('viewer', 'Lector')], default='owner', max_length=20),
        ),
    ]
